### ISSUE TITLE
mini lcd 12864 v2.1 

### ISSUE THREAD

**Issue by petitphilou28** [FYSETC/FYSETC-Cheetah-v2#3]
hi,
i can switch on my fysetc lcd v2.1 on cheetah but nothing appear...

here is my setup...

[display]
lcd_type: uc1701
cs_pin: PB15
a0_pin: PB12
rst_pin: PB13
contrast: 63
encoder_pins: ^PC10, ^PC11
click_pin: ^!PC12
## Some micro-controller boards may require an spi bus to be specified:
#spi_bus: spi
## Alternatively, some micro-controller boards may work with software spi:
spi_software_miso_pin: PA6
spi_software_mosi_pin: PA7
spi_software_sclk_pin: PA5

#[output_pin beeper]
#pin: EXP2_10

[neopixel fysetc_mini12864]
pin: PB0
chain_count: 3
color_order: RGB
initial_RED: 0.1
initial_GREEN: 0.5
initial_BLUE: 0.0

[delayed_gcode setdisplayneopixel]
initial_duration: 1
gcode:
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=1 BLUE=1 INDEX=1 TRANSMIT=0
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=2 TRANSMIT=0
        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=3

**Comment by lbibass** [comment]
How did you fix this?
